# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base_ps/base_ps.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps || ORIG_REF_NAME==base_ps} -quiet] -quiet

# IP: bd/base_ps/ip/base_ps_processing_system7_0_0/base_ps_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps_processing_system7_0_0 || ORIG_REF_NAME==base_ps_processing_system7_0_0} -quiet] -quiet

# XDC: /home/boernerc20/zc702_soc/zc702_soc.gen/sources_1/bd/base_ps/base_ps_ooc.xdc
